# Configuración generada por el Sistema de Gestión de Aplicaciones

app.nombre=Prueba
app.descripcion=
app.lenguaje=JAVA
app.tipoProyecto=DEMO

# Base de datos
app.baseDatos.tipo=POSTGRESQL
app.baseDatos.modo=local
app.baseDatos.nombre=demo
app.baseDatos.usuario=demo
app.baseDatos.password=demo

# CI/CD
app.cicd.proveedor=GITHUB
app.cicd.repoGit=davidtome97/prueba
app.cicd.sonarProjectKey=davidtome97_prueba

# Despliegue
app.despliegue.puertoInterno=8081
app.despliegue.nombreImagenEcr=
