# Configuración generada por el Sistema de Gestión de Aplicaciones

app.nombre=Prueba
app.descripcion=
app.lenguaje=JAVA
app.tipoProyecto=DEMO

# Base de datos
app.baseDatos.tipo=MYSQL
app.baseDatos.modo=local
app.baseDatos.nombre=root
app.baseDatos.usuario=root
app.baseDatos.password=root

# CI/CD
app.cicd.proveedor=GITHUB
app.cicd.repoGit=
app.cicd.sonarProjectKey=

# Despliegue
app.despliegue.puertoInterno=8081
app.despliegue.nombreImagenEcr=
